name: railway_tickets_sale_system

x-common-healthcheck: &default-healthcheck
  interval: 10s
  timeout: 5s
  retries: 5

services:
  # web_api:
  #   image: web_api
  #   container_name: web_api
  #   hostname: web_api
  #   restart: unless-stopped
  #   environment:
  #     - RabbitMQ__Uri=rabbitmq://rabbitmq
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - "5003:8080"
  #     - "8081:8081"
  #   networks:
  #     - app_network
  #   depends_on:
  #     message_broker:
  #       condition: service_healthy

  message_broker:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      <<: *default-healthcheck
    depends_on:
      sql_db:
        condition: service_healthy
      graph_db:
        condition: service_healthy

  sql_db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql_server_2025
    hostname: mssql2025
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1"]
      <<: *default-healthcheck

  graph_db:
    image: neo4j:5.12.0
    container_name: neo4j
    restart: unless-stopped
    hostname: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "neo4j-admin server status || exit 1"]
      <<: *default-healthcheck
  
  db_initializer:
    image: db_initializer
    container_name: db_initializer
    hostname: db_initializer
    volumes:
      - ./src/db/DatabaseInitializer/res:/app/res
    depends_on:
      sql_db:
        condition: service_healthy
      graph_db:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mssql_data:
  neo4j_data:
  neo4j_logs:
  rabbitmq_data:

networks:
  app_network:
    driver: bridge