<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>67198889-ccc1-4cdc-9193-427d4e46d813</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.5.10" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.9.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contacts\Contracts.csproj" />
  </ItemGroup>

</Project>
